### Promise



**支持串行任务**

- 支持串行异常处理，如果当前promise出现异常并且不传onRejected和catch，会一层一层向下传递
- onRejected和catch函数返回一个promise，value为函数返回值，reason为函数执行时的异常。
- 添加finally方法


```js
var PENDING = 'pending';
var FULFILLED = 'fulfilled';
var REJECTED = 'rejected';

function MyPromise(excutor) {
  var self = this;
  self.value = null;
  self.reason = null;
  self.status = PENDING;
  self.onFulfilled = [];
  self.onRejected = [];
  function resolve(value) {
    if (value instanceof MyPromise) { // promise实例
      return value.then(resolve, reject);
    }
    if (self.status === PENDING) {
      setTimeout(function() {
        if (self.status === PENDING) { //事件循环机制，解决同时调用resolve和reject可以触发两次状态更改
          self.value = value;
          self.status = FULFILLED;
          for (var i = 0; i < self.onFulfilled.length; i++) {
            self.onFulfilled[i](self.value);
          }
        }
      });
    }
  }
  function reject(reason) {
    setTimeout(function() {
      if (self.status === PENDING) {
        self.reason = reason;
        self.status = REJECTED;
        for (var i = 0; i < self.onRejected.length; i++) {
          self.onRejected[i](self.reason);
        }
      }
    });
  }
  try {
    excutor(resolve, reject);
  } catch (e) {
    reject(e);
  }
}
MyPromise.prototype.then = function(onFulfilled, onRejected) {
  var self = this;
  if (self.status === PENDING) {
    return new MyPromise(function(resolve, reject) {
      self.onFulfilled.push(function (value) {
        try {
          var x = onFulfilled(value);
          resolvePromise(x, resolve, reject);
        } catch (e) {
          reject(e);
        }
      });
      self.onRejected.push(function (reason) {
        try {
          var x = onRejected(reason);
          resolvePromise(x, resolve, reject);
        } catch (e) {
          reject(e);
        }
      });
    });
  } else if (self.status === FULFILLED) {
    return new MyPromise(function (resolve, reject) {
      setTimeout(function () { // 按顺序执行promise，后面promise需要等待上一个promise状态更改才能执行
        try {
          var x = onFulfilled(self.value);
          resolvePromise(x, resolve, reject);
        } catch (e) {
          reject(e);
        }
      });
    })
  } else if (self.status === REJECTED) {
    return new MyPromise(function (resolve, reject) {
      setTimeout(function () {
        try {
          var x = onRejected(self.reason);
          resolvePromise(x, resolve, reject);
        } catch (e) {
          reject(e);
        }
      });
    })
  }
}

MyPromise.prototype.catch = function (onRejected) {
  return this.then(null, onRejected);
}

// 返回一个Promise，在promise执行结束时，无论结果是fulfilled或者是rejected，在执行then()和catch()后，都会执行finally指定的回调函数
MyPromise.prototype.finally = function (fn) {
  return this.then(function (v) {
    setTimeout(fn);
    return v;
  }, function (e) {
    setTimeout(fn);
    throw e;
  })
}


function resolvePromise(x, resolve, reject) {
  if (x instanceof MyPromise) {
    x.then(function (y) { // y仍有可能是PROMISE
      resolvePromise(y, resolve, reject);
    })
  } else {
    resolve(x);
  }
}


// 测试
var p = new MyPromise(function (resolve) {
  throw new Error()
})
setTimeout(function () {
  p.then(function (value) {
    console.log(value)
  }, function (error) { throw 1 }).catch(function (e) {
    console.log(e)
  }).then(function (value) {
    console.log(value)
  })
})
```